version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["./waitPostgres.sh",  "db", "/go/src/bin/URLshortener"]
    environment:
      - DB_PASSWORD=pswrdroot
      - STORAGE=POSTGRES

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=pswrdroot
    ports:
      - 5432:5432